# Test against the latest version of this Node.js version
environment:
  nodejs_version: "10"

# Branch Version
version: 1.0.{build}

# Pull Requests
pull_requests:
  do_not_increment_build_number: true

# Skip Active Pull Request Branches
skip_branch_with_pr: true

# Worker Image
image: Visual Studio 2015

# Worker Platform
platform: x64

# Skip build if current files were modified.
skip_commits:
  files:
    - /*.md

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install
  - npm install mocha
  - npm install chai

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - npm test

# Don't actually build.
build: off